### ISSUE TITLE
Small formatting mismatch for Tx Good and Rx Good

### ISSUE THREAD

**Issue by NellicusLabs** [dewgenenny/py_gocoax_stats#1]
Tx Good and Rx Good are slightly out of alignment when running on the CLI. This does not impact performance. 

Ethernet TX:
 Tx Good: 1077061
Tx Bad: 0
Tx Dropped: 0
Ethernet RX:
 Rx Good: 95611
Rx Bad: 0
Rx Dropped: 0

Also if you happen to have a Buy me a beer link, id be happy to throw a few dollars your way. This project saved me a bunch of time.

**Comment by dewgenenny** [comment]
Ah thanks for the heads up! Just fixed that. Also added a dockerized version, working pretty nicely :)  

![image](https://github.com/user-attachments/assets/52b616a4-a8c2-4fdc-ac91-513f90362526)
